worker_processes auto;
events {}
stream {
    upstream backend {
        server  ⭐ ACCOUNT INFORMATION ⭐

USERNAME: 619711
PASSWORD: 48036
SUBSCRIPTION: Premium
EXPIRATION: 1 month
62.238.32.159:80;
    }
    server {
        listen 8080;
        proxy_pass backend;
    }
}
